In [1]:
import pandas as pd
import numpy as np

## EMOGI

In [2]:
emogi_predictions = pd.read_csv('../../../../../../../../s/project/gene_embedding/input_data/cancer_eval/emogi_predictions.tsv', sep='\t')
emogi_predictions

,ID,Name,label,Prob_pos_1,Prob_pos_2,Prob_pos_3,Prob_pos_4,Prob_pos_5,Prob_pos_6,Prob_pos_7,...,Prob_pos_9,Prob_pos_10,Num_Pos,Mean_Pred,Std_Pred,NCG_Known_Cancer_Gene,NCG_Candidate_Cancer_Gene,OncoKB_Cancer_Gene,Bailey_et_al_Cancer_Gene,ONGene_Oncogene
0,ENSG00000100393,EP300,True,1.0,1.0,1.0,1.0,1.0,1.0,1.0,...,1.0,1.0,10,1.0,0.0,True,False,True,True,False
1,ENSG00000133703,KRAS,True,1.0,1.0,1.0,1.0,1.0,1.0,1.0,...,1.0,1.0,10,1.0,0.0,True,False,True,True,True
2,ENSG00000155657,TTN,False,1.0,1.0,1.0,1.0,1.0,1.0,1.0,...,1.0,1.0,10,1.0,0.0,False,True,False,False,False
3,ENSG00000284792,PTEN,True,1.0,1.0,1.0,1.0,1.0,1.0,1.0,...,1.0,1.0,10,1.0,0.0,True,False,True,True,False
4,ENSG00000039068,CDH1,True,1.0,1.0,1.0,1.0,1.0,1.0,1.0,...,1.0,1.0,10,1.0,0.0,True,False,True,True,True
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
13622,ENSG00000266200,PNLIPRP2,False,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0,0.0,0.0,False,False,False,False,False
13623,ENSG00000125375,DMAC2L,False,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0,0.0,0.0,False,False,False,False,False
13624,ENSG00000173662,TAS1R1,False,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0,0.0,0.0,False,False,False,False,False
13625,ENSG00000197084,LCE1C,False,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0,0.0,0.0,False,False,False,False,False
13626,ENSG00000102924,CBLN1,False,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0,0.0,0.0,False,False,False,False,False

In [3]:
emogi_predictions2 = pd.read_csv('../../../../../../../../s/project/gene_embedding/input_data/cancer_eval/emogi_predictions2.tsv', sep='\t')
emogi_predictions2

               gene_id  label      pred
0      ENSG00000121879   True  5.293305
1      ENSG00000149311   True  5.293305
2      ENSG00000167548   True  5.293305
3      ENSG00000100393   True  5.293305
4      ENSG00000133703   True  5.293305
...                ...    ...       ...
13174  ENSG00000169344  False -5.293305
13175  ENSG00000167080  False -5.293305
13176  ENSG00000237388  False -5.293305
13177  ENSG00000254834  False -5.293305
13178  ENSG00000173464  False -5.293305

[13179 rows x 3 columns]

In [4]:
emogi_train_test = pd.read_csv('../../../../../../../../s/project/gene_embedding/input_data/cancer_eval/emogi_train_test.tsv', sep='\t')
emogi_train_test

              gene_id  mask      y dataset
0     ENSG00000232957  True  False   train
1     ENSG00000131966  True  False   train
2     ENSG00000133703  True   True   train
3     ENSG00000136240  True  False   train
4     ENSG00000137171  True  False   train
...               ...   ...    ...     ...
2953  ENSG00000256045  True  False    test
2954  ENSG00000151967  True  False    test
2955  ENSG00000256222  True  False    test
2956  ENSG00000269028  True  False    test
2957  ENSG00000173464  True  False    test

[2958 rows x 4 columns]

In [5]:
disease_gene_table = pd.read_csv('../../../../../../../../s/project/gene_embedding/input_data/disease_gene_eval/disease_gene_table.tsv', sep='\t')
disease_gene_table

              gene_id        disease
0     ENSG00000198691  Ophthalmology
1     ENSG00000101986  Ophthalmology
2     ENSG00000100997  Ophthalmology
3     ENSG00000107897  Ophthalmology
4     ENSG00000100412  Ophthalmology
...               ...            ...
2108  ENSG00000213689            IEI
2109  ENSG00000071553            IEI
2110  ENSG00000126759            IEI
2111  ENSG00000160211            IEI
2112  ENSG00000147050            IEI

[2113 rows x 2 columns]